package com.phocas.asset.rest.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "AssetEvent")
public class AssetEvent {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute(attributeName = "asset")
    private int asset;
    @DynamoDBAttribute(attributeName = "trip")
    private int trip;
    @DynamoDBAttribute(attributeName = "x")
    private double x;
    @DynamoDBAttribute(attributeName = "y")
    private double y;
    @DynamoDBAttribute(attributeName = "speed")
    private double speed;
    @DynamoDBAttribute(attributeName = "created")
    private long created;
}
