package com.phocas.asset.rest.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Builder;
import lombok.Value;

@Value
@Builder
@DynamoDBTable(tableName = "Asset")
public class AssetEvent {
    private int id;
    private int asset;
    private int trip;
    private double x;
    private double y;
    private double speed;
    private long created;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public int getId() {
        return id;
    }

    @DynamoDBAttribute(attributeName = "asset")
    public int getAsset() {
        return asset;
    }

    @DynamoDBAttribute(attributeName = "trip")
    public int getTrip() {
        return trip;
    }

    @DynamoDBAttribute(attributeName = "x")
    public double getX() {
        return x;
    }

    @DynamoDBAttribute(attributeName = "y")
    public double getY() {
        return y;
    }

    @DynamoDBAttribute(attributeName = "speed")
    public double getSpeed() {
        return speed;
    }

    @DynamoDBAttribute(attributeName = "created")
    public long getCreated() {
        return created;
    }
}
